### ISSUE TITLE
Error on Compilation

### ISSUE THREAD

**Issue by Soumya624** [GeomScale/volesti#258] opened 2023-01-05 10:47 UTC
**Describe the bug**
Error is showing on running " cmake -DLP_SOLVE=/usr/lib/lp_solve/liblpsolve55.so .. " on WSL

![Screenshot 2023-01-05 161629](https://user-images.githubusercontent.com/63846042/210762293-0530553c-4c22-4211-a417-c47f4132ff04.jpg)

**Comment by vissarion** [comment] 2023-01-05 11:49
Thanks for your report. Could you please post the contents of `config.log`?

**Comment by Soumya624** [comment] 2023-01-07 16:39
[config.log](https://github.com/GeomScale/volesti/files/10366723/config.log)

**Comment by vissarion** [comment] 2023-01-09 10:10
Thanks, it seems that the issue is related to the `ieeefp.h` file which is probably missing from your system (or the script cannot find it). You could try installing it.

**Comment by Soumya624** [comment] 2023-01-11 07:55
Thanks.
It partially solved the issue. Please find the attached image for the clarification

![Screenshot 2023-01-11 132452](https://user-images.githubusercontent.com/63846042/211749336-ff632534-a8e4-4071-9589-27e84489d93e.jpg)

**Comment by vissarion** [comment] 2023-01-11 08:53
Thanks. How did you resolve the issue? 
Now you have to install `mkl` to solve the new issue.

**Comment by Soumya624** [comment] 2023-01-14 15:47
Thanks!

For the previous issue i just ran the following command in the terminal:
sudo apt-get install libc6-dev-i386

And to install mkl:
wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
sudo sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'
sudo apt-get update
sudo apt-get install intel-mkl-2020.4-912
sudo sh -c "echo /opt/intel/mkl/lib/intel64 > /etc/ld.so.conf.d/intel-mkl.conf"
sudo ldconfig
export CPLUS_INCLUDE_PATH="/opt/intel/mkl/include:$CPLUS_INCLUDE_PATH"

But, currently i am getting this. And that's why all the tests are getting failed:
![Screenshot 2023-01-14 210858](https://user-images.githubusercontent.com/63846042/212480505-179016db-0a08-4588-84d7-bd1802dab3f5.jpg)

**Comment by vissarion** [comment] 2023-01-15 19:33
You need `lpsolve` installed and also to tell cmake where to find it i.e. `cmake -DLP_SOLVE=/usr/lib/lpsolve/liblpsolve55.so`

**Comment by Soumya624** [comment] 2023-01-16 19:13
It seems like we are trying to convert an int* to a long long int* in the initialization of some variable

![o1](https://user-images.githubusercontent.com/63846042/212751209-d6891aab-08b9-438c-9af5-b835b2420f40.jpg)
![o2](https://user-images.githubusercontent.com/63846042/212751303-e2c915d0-9682-413f-ac0a-83a437aafde1.jpg)

**Comment by vissarion** [comment] 2023-01-17 07:56
I cannot reproduce locally your error. It comes from https://github.com/GeomScale/volesti/blob/develop/include/convex_bodies/vpolytope.h#L594 

What compiler and version are you using? What is your linux system type and version (installed inside Windows)? What version of volesti are you trying to compile?

**Comment by Soumya624** [comment] 2023-01-18 09:06
I am using Ubuntu 22.04.1 LTS (GNU/Linux 5.10.16.3-microsoft-standard-WSL2 x86_64). And volesti vesion 1.1.2-3

**Comment by Soumya624** [comment] 2023-01-20 03:20
Fixed the bug. Should I add few changes to this CONTRIBUTING.md in a PR?

**Comment by vissarion** [comment] 2023-01-20 10:01
Yes, feel free to open a PR and somebody will review it. Also feel free to close this issue if is resolved.

**Closed as completed** 2023-01-20 15:05 UTC

**Comment by LongPham7** [comment] 2023-05-06 19:57
@Soumya624 @vissarion I encountered the same issue as [the one mentioned in this thread](https://github.com/GeomScale/volesti/issues/258#issuecomment-1384458115) where the code tries to cast `int*` to `long long int*`. How did you get around this issue? Thanks!

**Comment by Soumya624** [comment] 2023-05-07 20:51
@LongPham7
Here, the code was trying to convert a pointer to an array of int to a pointer to an array of long long int (lapack_int*, which is defined as long long int*).

To fix this issue, I had changed the type of the perm variable to int*. And it worked for me (It should match the type of the indices().data() method).

**Comment by LongPham7** [comment] 2023-05-08 14:32
@Soumya624 Great. Thanks a lot for your help!
